#!/usr/bin/env make -f
# file name: Makefile
# description: TODO
# author: amoblin <amoblin@gmail.com>
# create date: {{date}}
# This file is created from $MARBOO_HOME/.media/starts/Makefile
# 本文件由 $MARBOO_HOME/.media/starts/Makefile　复制而来

.PHONY: 
