# -*- coding: utf-8 -*-
# author: amoblin <amoblin@gmail.com.com>
# file name: Podfile
# create date: {{date}}
# This file is created from $MARBOO_HOME/.media/starts/Podfile
# 本文件由 $MARBOO_HOME/.media/starts/Podfile 复制而来
 
platform :ios, "7.0"
source "https://github.com/CocoaPods/Specs.git"

pod "ReactiveCocoa", "~> 2.3.1"

pod "ReactiveViewModel", "~> 0.2"

pod "UMengAnalytics", "~> 3.1.8"

pod "UMengFeedback", "~> 2.0"

pod "Masonry"
