#!/usr/bin/env rake -f
# coding: utf-8
# file name: Rakefile
# description: TODO
# author: amoblin <amoblin@gmail.com>
# create date: {{date}}
# This file is created from $MARBOO_HOME/.media/starts/Rakefile
# 本文件由 $MARBOO_HOME/.media/starts/Rakefile　复制而来
